language: go

go:
  - "1.10.2"

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  local_dir: public
  repo: serializingme/serializingme.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  fqdn: www.serializing.me
  github_token: $GITHUB_TOKEN
  on:
    branch: master
