baseurl = "https://www.serializing.me"
languageCode = "en-gb"
title = "SerializingMe"
theme = "serializingme"
removePathAccents = true

[permalinks]
post = "/:year/:month/:day/:slug/"
page = "/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[markup.highlight]
style = 'native'

[params]
description = "Yet another blog about personal projects and research, thoughts and ideas."
#analytics = ""
#adsense = ""

[params.author]
name = "Duarte Silva"

[[params.author.social]]
name = "Mastodon"
icon = "fab fa-mastodon"
url = "https://infosec.exchange/@serializingme"

[[params.author.social]]
name = "Twitch"
icon = "fab fa-twitch"
url = "https://www.twitch.tv/serializingme"

[[params.author.social]]
name = "Discord"
icon = "fab fa-discord"
url = "https://discord.gg/NS5qHT4"

[[params.author.social]]
name = "YouTube"
icon = "fab fa-youtube"
url = "https://www.youtube.com/serializingme"

[[params.author.social]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/serializingme"

[[params.author.social]]
name = "Bugcrowd"
icon = "fas fa-bug"
url = "https://bugcrowd.com/serializingme"

[[params.author.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/serializingme"

[params.page]
post = "/post/"
project = "/project/"

# Main menu links.
[[menu.main]]
name = "Blog"
url = "/post/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/project/"
weight = 2
