baseurl = "https://www.serializing.me"
languageCode = "en-gb"
title = "SerializingMe"
theme = "serializingme"
removePathAccents = true

[permalinks]
post = "/:year/:month/:day/:slug/"
page = "/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Yet another blog about personal projects and research, thoughts and ideas."
#analytics = ""
#adsense = ""

[params.author]
name = "Duarte Silva"
twitter = "@serializingme"

[[params.author.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/serializingme"

[[params.author.social]]
name = "YouTube"
icon = "fab fa-youtube"
url = "https://www.youtube.com/c/serializingme"

[[params.author.social]]
name = "Google+"
icon = "fab fa-google-plus"
url = "https://plus.google.com/+SerializingMe"

[[params.author.social]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/serializingme"

[[params.author.social]]
name = "Bugcrowd"
icon = "fas fa-bug"
url = "https://bugcrowd.com/serializingme"

[[params.author.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/feeds/"

[params.page]
post = "/post/"
project = "/project/"

# To other pages.
[[params.page.footer]]
name = "Licensing"
icon = "fas fa-copyright"
url = "/licensing/"

[[params.page.footer]]
name = "Privacy"
icon = "fas fa-eye"
url = "/privacy/"

[[params.page.footer]]
name = "Security"
icon = "fas fa-shield-alt"
url = "/security/"

[[params.page.footer]]
name = "Contacts"
icon = "fas fa-envelope"
url = "/contacts/"

# Main menu links.
[[menu.main]]
name = "Blog"
url = "/post/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/project/"
weight = 2

[[menu.main]]
name = "Contributions"
url = "/contributions/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/"
weight = 4
