name: Main Jobs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'

      - name: Setup Analytics and AdSense
        env:
          ANALYTICS_TOKEN: ${{ secrets.ANALYTICS_TOKEN }}
          ADSENSE_TOKEN: ${{ secrets.ADSENSE_TOKEN }}
        run: |
          if [ -z ${ANALYTICS_TOKEN} ]; then echo "No analytics token set"; else sed -ri "s/^#analytics = \"\"\$/analytics = \"$ANALYTICS_TOKEN\"/g" config.toml; fi
          if [ -z ${ADSENSE_TOKEN} ]; then echo "No AdSense token set"; else sed -ri "s/^#adsense = \"\"\$/adsense = \"$ADSENSE_TOKEN\"/g" config.toml; fi

      - name: Build Website
        run: hugo

      - name: GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: www.serializing.me
